language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libprotobuf-dev p7zip-full wget

install:
 - wget -O boost_1_65_1.tar.gz https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
 - tar xf boost_1_65_1.tar.gz
 - cd boost_1_65_1
 - ./bootstrap.sh --prefix=/usr/local
 - travis_wait 30 ./b2 -d0
 - sudo ./b2 install -d0
 - cd ..

script:
 - cmake -DCMAKE_BUILD_TYPE=Release .
 - cmake --build .
 - cmake --build . --target test
