language: cpp
sudo: required
services:
 - docker

before_install:
 - docker pull seeker7/cxx-dev
 - docker run -itd --name builder seeker7/cxx-dev
 - docker exec builder git clone --recursive https://github.com/fabricetriboix/skal.git

script:
 - docker exec builder cmake -Hskal -Boutput
 - docker exec builder cmake --build output
 - docker exec builder cmake --build output --target test
