language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libprotobuf-dev p7zip-full wget
 - >
   wget https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.7z
   && 7za x boost_1_64_0.7z
   && cd boost_1_64_0/tools/build
   && ./bootstrap.sh
   && ./b2 --prefix=/usr/local install
   && cd ../..
   && b2 --prefix=/usr/local toolset=gcc link=static install

script: >
    mkdir ../build
    && cd ../build
    && cmake -DCMAKE_BUILD_TYPE=Release ../skal
    && cmake --build .
    && cmake --build . --target
