language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - wget
            - curl
            - unzip
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
 - eval "${MATRIX_EVAL}"
 - sudo ln -sf /usr/bin/g++-7 /usr/bin/g++
 - sudo ln -sf /usr/bin/gcc /usr/bin/gcc-7
 - wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
 - tar xf boost_1_65_1.tar.gz
 - cd boost_1_65_1
 - ./bootstrap.sh --prefix=/usr/local --with-toolset=gcc
 - travis_wait 30 ./b2 -d0
 - sudo ./b2 install -d0
 - cd ..
 - wget https://cmake.org/files/v3.10/cmake-3.10.0.tar.gz
 - tar xf cmake-3.10.0.tar.gz
 - cd cmake-3.10.0
 - ./bootstrap > /dev/null
 - make > /dev/null
 - sudo make install
 - cd ..
 - git clone --recursive https://github.com/google/protobuf.git
 - cd protobuf
 - ./autogen.sh
 - ./configure > /dev/null
 - make > /dev/null
 - sudo make install
 - sudo ldconfig
 - cd ..

script:
 - g++ --version
 - cmake --version
 - cd ..
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ../skal
 - cat CMakeFiles/skal.dir/build.make
 - make
 - make test
