language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libprotobuf-dev
 - sudo apt-get install libboost-atomic-dev libboost-chrono-dev
 - sudo apt-get install libboost-filesystem-dev libboost-thread-dev

script: >
    mkdir ../build
    && cd ../build
    && cmake -DCMAKE_BUILD_TYPE=Release ../skal
    && cmake --build .
    && cmake --build . --target
