Import('variant')

import os

artefacts = {}

srcs = [os.path.join("src", "skald.c")]
artefacts['objs'] = [variant['env'].StaticObject(src) for src in srcs]
artefacts['testsrcs'] = [os.path.join("test", "unittest-skald.c")]

skaldsrcs = [os.path.join("src", "main.c")]
artefacts['skaldobjs'] = [variant['env'].StaticObject(src) for src in skaldsrcs]

Return('artefacts')
