Import('variant')

import os

artefacts = {}

artefacts['incs'] = [os.path.join("include", "skalplf.h")]
srcs = [os.path.join("src", "skalplf.c")]
artefacts['objs'] = [variant['env'].StaticObject(src) for src in srcs]
artefacts['testsrcs'] = [os.path.join("test", "unittest.c")]

testmain_src = os.path.join("src", "rttestmain.c")
artefacts['rttestmainobj'] = variant['env'].StaticObject(testmain_src)

Return('artefacts')
